// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJf5h2c2WrqAitl3-U4UMW5K-LPPN4iAQ',
    appId: '1:881269937606:web:3566e0d0243c890599cec7',
    messagingSenderId: '881269937606',
    projectId: 'housepal-7ded9',
    authDomain: 'housepal-7ded9.firebaseapp.com',
    storageBucket: 'housepal-7ded9.firebasestorage.app',
    measurementId: 'G-ZMECV71RZ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6B4bXppTz2iBZYR90GXJd8sR5gJ4DZZs',
    appId: '1:881269937606:android:5485079b021898d599cec7',
    messagingSenderId: '881269937606',
    projectId: 'housepal-7ded9',
    storageBucket: 'housepal-7ded9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDo46guRtS8P-F8GGXeH2V6JGbFmHaEHa8',
    appId: '1:881269937606:ios:e8354d0c0e5d504b99cec7',
    messagingSenderId: '881269937606',
    projectId: 'housepal-7ded9',
    storageBucket: 'housepal-7ded9.firebasestorage.app',
    iosBundleId: 'com.example.housePal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDo46guRtS8P-F8GGXeH2V6JGbFmHaEHa8',
    appId: '1:881269937606:ios:e8354d0c0e5d504b99cec7',
    messagingSenderId: '881269937606',
    projectId: 'housepal-7ded9',
    storageBucket: 'housepal-7ded9.firebasestorage.app',
    iosBundleId: 'com.example.housePal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJf5h2c2WrqAitl3-U4UMW5K-LPPN4iAQ',
    appId: '1:881269937606:web:bbd17f5db36f7a7599cec7',
    messagingSenderId: '881269937606',
    projectId: 'housepal-7ded9',
    authDomain: 'housepal-7ded9.firebaseapp.com',
    storageBucket: 'housepal-7ded9.firebasestorage.app',
    measurementId: 'G-438C0F1X6C',
  );
}
